name: Test Self Hosted Runner

on:
  push:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Test runner
        run: |
          echo "Runner is working!"
          whoami
          uname -a
          java -version
          mvn -version
          git --version
